"""L2 order book, the liquidity-evaporation model, and pre-trade price bands.

Amplifier 2 from the research brief: liquidity disappears exactly when it is
needed. On 10 Oct 2025 BTC top-of-book depth shrank by more than 90% as market
makers widened spreads or stepped away entirely. The book you stress-test
against in calm markets does not exist in the crash, so depth here is a
function of realised volatility, not a static ladder replayed from a quiet day.

The book is modelled as a parametric depth curve rather than a queue of
individual orders. That is a deliberate simplification: nothing in this project
turns on queue priority, and a curve is exactly reproducible, cheap enough to
run 1,200 accounts over hundreds of ticks, and legible to a judge reading the
code. What it does model faithfully is the thing that matters -- walking a
forced sale through thinning depth produces real slippage, and that slippage
feeds back into the mark that triggers the next liquidation.

Price formation has two parts:

    book_mid = fair_value * (1 + venue_dislocation) * (1 - pressure)

`fair_value` is exogenous (the scenario's true price). `pressure` accumulates
from net forced flow measured against current depth and decays with a
half-life, which is what turns a liquidation cascade into a spiral rather than
a single step. `venue_dislocation` is how a venue-local wick is injected: the
book prints a price the rest of the world does not have, which is the setup for
every Abnormal Price Event in this simulator.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

BPS: float = 1e-4


@dataclass(frozen=True, slots=True)
class BookParams:
    """Microstructure of one market. Scenario-owned, not policy-owned: this is
    what the world does, not what MochaTrade decides."""

    depth_1pct_notional: float
    """Resting notional per side within 1% of mid, in INR, in calm markets."""

    decay_per_pct: float = 0.12
    """Exponential decay of resting size with distance from mid. Calibrated so
    cumulative depth within 5% is ~4x the 1% band and within 20% is ~8x, which
    is the shape of a real perp book. Higher means a thinner tail, so a large
    forced sale runs out of book sooner."""

    level_bps: int = 5
    n_levels: int = 400
    """400 levels at 5bps covers 20% from mid. Beyond that the book is empty and
    a market order cannot fill, which is itself a failure mode worth showing."""

    max_reach_pct: float = 3.0
    """How far from mid a single tick of market orders can reach. Depth further
    out exists, but it is not instantaneously accessible: resting orders that
    deep are replenished over seconds, not within one second.

    This is physics, not policy, and the distinction matters. Without it,
    "unthrottled" would mean the liquidation engine can sweep the entire 20%
    book inside one second, which no matching engine can do and which collapses
    the whole cascade into three ticks. The risk CONTROL is the participation
    cap in RiskParams; this is the venue capacity that exists either way.
    Anything unfilled simply requeues: the account stays open and is
    re-evaluated on the next tick, which is what produces a cascade that grinds
    rather than one that detonates.
    """

    base_spread_bps: float = 4.0
    max_spread_bps: float = 250.0

    min_liquidity_frac: float = 0.06
    """Floor on resting depth under maximum stress. 0.06 reproduces the >90%
    top-of-book collapse observed on 10 Oct 2025."""

    withdrawal_sensitivity: float = 0.0035
    """How fast makers step away per bp of 1-minute realised volatility.
    Calibrated against 10 Oct 2025: a 2% move halves resting depth and a 10%
    move takes it to the floor, i.e. the >90% top-of-book collapse observed."""

    withdrawal_speed: float = 0.35
    """Per-tick move toward the stress target. Makers pull fast..."""

    heal_speed: float = 0.04
    """...and come back slowly. Asymmetry is the point."""

    impact_coef_bps: float = 110.0
    """Downward pressure in bps generated by forced flow equal to 100% of the
    1%-band depth. Consuming the whole 1% band moves the mid by about 1% by
    definition; the extra 10bps is the persistent component."""

    impact_halflife_seconds: float = 25.0

    arbitrage_scale_bps: float = 400.0
    """Dip-buying. The further the book sits below fair value, the more
    attractive it is to arbitrage against the composite, so accumulated
    pressure decays faster the deeper it goes. Without this the cascade has no
    restoring force at all and every run pins against the ceiling, which
    flattens the difference between control stacks and makes the comparison
    meaningless."""

    max_pressure_bps: float = 6000.0
    """Ceiling on accumulated downward pressure: 60%. Beyond this the model is
    no longer claiming to represent a perp book, and on a HIP-3 market a >50%
    daily move triggers validator review for slashing anyway."""


@dataclass(frozen=True, slots=True)
class Fill:
    """The result of walking a market order through the book."""

    requested_notional: float
    filled_notional: float
    filled_qty: float
    avg_price: float
    worst_price: float
    slippage_bps: float
    exhausted: bool

    @property
    def unfilled_notional(self) -> float:
        return max(0.0, self.requested_notional - self.filled_notional)


@dataclass(frozen=True, slots=True)
class DepthSnapshot:
    """Resting depth left on each side at the end of a tick, bucketed.

    `bids[i]` is the INR notional resting between i*bucket_bps and
    (i+1)*bucket_bps below the best bid; `asks[i]` the same above the best ask.
    Prices are implied by the touch, so a snapshot is sizes only.
    """

    bucket_bps: int
    bids: tuple[int, ...]
    asks: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class BandCheck:
    """Pre-trade price band verdict. CFTC/FIA's pre-trade layer: reject orders
    outside reference +/- variant, dynamic and regularly recalculated."""

    accepted: bool
    reference: float
    lower: float
    upper: float
    price: float


class Book:
    """A single market's book. Deterministic: no randomness lives in here."""

    __slots__ = (
        "params",
        "fair_value",
        "venue_dislocation",
        "liquidity_frac",
        "pressure_bps",
        "_mid",
        "_weights",
        "_offsets",
        "_norm_1pct",
        "_impact_decay",
        "_consumed_bid",
        "_consumed_ask",
    )

    def __init__(self, params: BookParams, initial_price: float) -> None:
        self.params = params
        self.fair_value = initial_price
        self.venue_dislocation = 0.0
        self.liquidity_frac = 1.0
        self.pressure_bps = 0.0
        self._consumed_bid = 0.0
        self._consumed_ask = 0.0
        self._mid = initial_price

        # Precompute the level shape once. Level i sits (i+1)*level_bps from mid.
        offsets: list[float] = []
        weights: list[float] = []
        for i in range(params.n_levels):
            dist_pct = (i + 1) * params.level_bps * BPS * 100.0
            offsets.append(dist_pct)
            weights.append(math.exp(-params.decay_per_pct * dist_pct))
        self._offsets = tuple(offsets)
        self._weights = tuple(weights)

        # Normalise so the levels inside 1% sum to depth_1pct_notional.
        inside = math.fsum(w for o, w in zip(offsets, weights) if o <= 1.0)
        self._norm_1pct = params.depth_1pct_notional / inside if inside > 0 else 0.0

        self._impact_decay = 0.0  # recomputed per tick from current pressure

    # -- state -------------------------------------------------------------

    @property
    def mid(self) -> float:
        return self._mid

    @property
    def spread_bps(self) -> float:
        """Spread widens as makers withdraw. Market makers 'widened their spreads
        dramatically or stepped away altogether' -- both, here."""
        p = self.params
        widened = p.base_spread_bps / max(self.liquidity_frac, 1e-6)
        return min(p.max_spread_bps, widened)

    @property
    def best_bid(self) -> float:
        return self._mid * (1.0 - self.spread_bps * BPS / 2.0)

    @property
    def best_ask(self) -> float:
        return self._mid * (1.0 + self.spread_bps * BPS / 2.0)

    def depth_within(self, pct: float) -> float:
        """Resting notional per side within `pct` percent of mid, after
        withdrawal. This is what the liquidation participation cap is measured
        against."""
        total = math.fsum(
            w for o, w in zip(self._offsets, self._weights) if o <= pct
        )
        return total * self._norm_1pct * self.liquidity_frac

    def depth_pct_of_baseline(self) -> float:
        """Current 1%-band depth as a fraction of the calm baseline. One of the
        gates the operator must clear before reopening."""
        return self.liquidity_frac

    # -- evolution ---------------------------------------------------------

    def update_liquidity(self, realised_vol_bps: float) -> None:
        """Makers withdraw as realised volatility rises, and return slowly."""
        p = self.params
        target = max(
            p.min_liquidity_frac,
            math.exp(-p.withdrawal_sensitivity * max(0.0, realised_vol_bps)),
        )
        speed = p.withdrawal_speed if target < self.liquidity_frac else p.heal_speed
        self.liquidity_frac += (target - self.liquidity_frac) * speed

    def apply_flow(self, net_sell_notional: float) -> None:
        """Feed net forced flow back into price. This is the spiral: the engine
        sells, the price falls, more accounts breach maintenance margin, the
        engine sells more. BitMEX, March 2020."""
        p = self.params
        depth = max(self.depth_within(1.0), 1.0)
        self.pressure_bps = min(
            p.max_pressure_bps,
            self.pressure_bps + p.impact_coef_bps * (net_sell_notional / depth),
        )

    def settle(self, fair_value: float, venue_dislocation: float) -> None:
        """Advance to the next tick: decay accumulated impact, then reprice."""
        self.fair_value = fair_value
        self.venue_dislocation = venue_dislocation
        # Resting orders taken during the previous tick are replenished now.
        self._consumed_bid = 0.0
        self._consumed_ask = 0.0
        p = self.params
        half_life = max(
            1e-6,
            p.impact_halflife_seconds
            / (1.0 + abs(self.pressure_bps) / max(1e-9, p.arbitrage_scale_bps)),
        )
        self._impact_decay = math.exp(-math.log(2.0) / half_life)
        self.pressure_bps = min(
            p.max_pressure_bps, self.pressure_bps * self._impact_decay
        )
        self._mid = fair_value * (1.0 + venue_dislocation) * (
            1.0 - self.pressure_bps * BPS
        )
        if self._mid <= 0.0:
            # A book cannot print a non-positive price; it runs out of bids
            # first. Clamp and let the exhaustion path report it.
            self._mid = fair_value * 0.01

    # -- execution ---------------------------------------------------------

    def reachable(self, *, sell: bool) -> float:
        """Depth a single tick of market orders can still consume on one side.

        Tracked per side. A sell takes bids and a buy takes asks; a single
        shared counter made a short liquidation skip ask levels nobody had
        touched, just because longs had sold into the bids earlier that tick.
        """
        gross = self.depth_within(self.params.max_reach_pct)
        return max(0.0, gross - (self._consumed_bid if sell else self._consumed_ask))

    @property
    def reachable_depth(self) -> float:
        """Bid-side reachable depth: what a forced sale can still take."""
        return self.reachable(sell=True)

    def consume(self, *, sell: bool, notional: float) -> None:
        """Record depth taken outside `walk`, e.g. by a call auction."""
        if sell:
            self._consumed_bid += max(0.0, notional)
        else:
            self._consumed_ask += max(0.0, notional)

    def walk(
        self, *, sell: bool, notional: float | None = None, qty: float | None = None
    ) -> Fill:
        """Walk a market order through resting depth and report the damage.

        Consumption is sequential WITHIN a tick: each order starts where the
        previous one stopped, and the book is replenished only on `settle`.
        Without this, a cascade of 800 liquidations in one tick would walk 800
        pristine copies of the same book and execute many multiples of the
        liquidity that actually exists -- which reads as an instant detonation
        rather than a cascade, and makes every throttle look pointless.

        Size the order by `qty` when closing a position and by `notional` when
        spending a budget. Sizing a position close by notional computed at the
        mark silently under-fills whenever the book trades away from the mark,
        leaving a residue on every close that has to be chased on later ticks.
        """
        if (notional is None) == (qty is None):
            raise ValueError("pass exactly one of notional= or qty=")
        start = self.best_bid if sell else self.best_ask
        by_qty = qty is not None
        want = (qty if by_qty else notional) or 0.0
        if want <= 0.0:
            return Fill(0.0, 0.0, 0.0, start, start, 0.0, False)

        sign = -1.0 if sell else 1.0
        remaining = want
        filled_notional = 0.0
        filled_qty = 0.0
        worst = start

        already = self._consumed_bid if sell else self._consumed_ask
        walked = 0.0
        for offset_pct, weight in zip(self._offsets, self._weights):
            if offset_pct > self.params.max_reach_pct:
                break
            level_notional = weight * self._norm_1pct * self.liquidity_frac
            if level_notional <= 0.0:
                continue
            # Skip past whatever earlier orders in this tick already took.
            if walked + level_notional <= already:
                walked += level_notional
                continue
            available = level_notional - max(0.0, already - walked)
            walked += level_notional

            price = start * (1.0 + sign * offset_pct / 100.0)
            if price <= 0.0:
                break
            capacity = available / price if by_qty else available
            take = capacity if capacity < remaining else remaining
            if take <= 0.0:
                continue
            taken_qty = take if by_qty else take / price
            filled_notional += taken_qty * price
            filled_qty += taken_qty
            worst = price
            remaining -= take
            if remaining <= 1e-9:
                break

        if sell:
            self._consumed_bid += filled_notional
        else:
            self._consumed_ask += filled_notional
        exhausted = remaining > 1e-9
        avg = filled_notional / filled_qty if filled_qty > 0 else start
        slippage = abs(avg - start) / start / BPS if start > 0 else 0.0
        return Fill(
            requested_notional=(want * start) if by_qty else want,
            filled_notional=filled_notional,
            filled_qty=filled_qty,
            avg_price=avg,
            worst_price=worst,
            slippage_bps=slippage,
            exhausted=exhausted,
        )

    def depth_snapshot(self, *, levels: int, bucket_bps: int) -> DepthSnapshot:
        """What is left in the book after this tick's consumption, per side.

        Consumption eats levels from the touch outward, so a tick of forced
        selling shows up as an emptied top of the bid side -- the thinning a
        depth ladder exists to show.
        """
        per = max(1, int(round(bucket_bps / self.params.level_bps)))

        def side(consumed: float) -> tuple[int, ...]:
            left = consumed
            out: list[int] = []
            for bucket in range(levels):
                total = 0.0
                for k in range(bucket * per, (bucket + 1) * per):
                    if k >= len(self._weights):
                        break
                    notional = self._weights[k] * self._norm_1pct * self.liquidity_frac
                    take = notional if notional < left else left
                    left -= take
                    total += notional - take
                out.append(int(round(total)))
            return tuple(out)

        return DepthSnapshot(
            bucket_bps=per * self.params.level_bps,
            bids=side(self._consumed_bid),
            asks=side(self._consumed_ask),
        )

    def resting_levels(self, *, sell: bool, bound: float) -> list[tuple[float, float]]:
        """Resting orders a call auction can match: bids at or above `bound`
        (for incoming sells) or asks at or below it (for incoming buys), as
        (price, quantity). An auction pools the whole book inside its collar,
        so the per-tick reach limit of continuous trading does not apply."""
        start = self.best_bid if sell else self.best_ask
        sign = -1.0 if sell else 1.0
        out: list[tuple[float, float]] = []
        for offset_pct, weight in zip(self._offsets, self._weights):
            price = start * (1.0 + sign * offset_pct / 100.0)
            if price <= 0.0 or (sell and price < bound) or (not sell and price > bound):
                break
            notional = weight * self._norm_1pct * self.liquidity_frac
            if notional > 0.0:
                out.append((price, notional / price))
        return out

    def set_mid(self, price: float) -> None:
        """Open continuous trading at a price discovered elsewhere -- a call
        auction's clearing price. Expressed as pressure, so it decays back
        toward fair value like any other impact."""
        base = self.fair_value * (1.0 + self.venue_dislocation)
        if base <= 0.0 or price <= 0.0:
            return
        self.pressure_bps = min(self.params.max_pressure_bps, (1.0 - price / base) / BPS)
        self._mid = base * (1.0 - self.pressure_bps * BPS)

    # -- pre-trade controls -------------------------------------------------

    def check_band(self, price: float, reference: float, band_pct: float) -> BandCheck:
        lower = reference * (1.0 - band_pct / 100.0)
        upper = reference * (1.0 + band_pct / 100.0)
        return BandCheck(
            accepted=lower <= price <= upper,
            reference=reference,
            lower=lower,
            upper=upper,
            price=price,
        )


@dataclass(slots=True)
class VolatilityTracker:
    """Rolling realised volatility, used to drive liquidity withdrawal.

    Measured as the absolute return over the window in bps, not a standard
    deviation: the thing that scares a market maker off the book is the size of
    the move, not its statistical shape.
    """

    window_ticks: int = 60
    _prices: list[float] = field(default_factory=list)

    def push(self, price: float) -> None:
        self._prices.append(price)
        if len(self._prices) > self.window_ticks:
            del self._prices[0]

    @property
    def realised_bps(self) -> float:
        if len(self._prices) < 2:
            return 0.0
        first = self._prices[0]
        if first <= 0.0:
            return 0.0
        lo = min(self._prices)
        hi = max(self._prices)
        return (hi - lo) / first / BPS
