# Generated by Django 5.2.17 on 2026-09-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simrun',
            name='policy_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of the parameter values this run actually executed against. Part of the cache key, because editing a margin tier does not bump RiskPolicy.version -- keying on the version alone would serve a stale run after a policy edit and quietly contradict the admin.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='simrun',
            index=models.Index(fields=['scenario', 'controls_enabled', 'seed', 'policy_fingerprint'], name='core_simrun_cachekey_idx'),
        ),
    ]
