# Generated by Django 5.2.17 on 2026-09-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simrun_policy_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceobservation',
            name='clamped',
            field=models.BooleanField(default=False, help_text='Capped against the median.'),
        ),
        migrations.AddField(
            model_name='priceobservation',
            name='raw_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='What the source actually printed. The gap to `price` is the clamp.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='priceobservation',
            name='rung',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Composite ladder rung 1-3; blank for derived prices.', null=True),
        ),
        migrations.AddField(
            model_name='priceobservation',
            name='used',
            field=models.BooleanField(default=False, help_text='Fed the published composite this tick.'),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='The price the composite used, after the outlier clamp. Blank when the source printed nothing -- a closed market or an unreachable venue -- and for the composite itself at ladder L4.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='source',
            field=models.CharField(choices=[('MOCHATRADE', 'MochaTrade mark'), ('COMPOSITE', 'Published composite (live)'), ('REFERENCE', 'Reference Composite (reconstructed)'), ('BINANCE', 'Binance spot'), ('OKX', 'OKX spot'), ('COINBASE', 'Coinbase spot'), ('KRAKEN', 'Kraken spot'), ('US_CASH', 'US cash market'), ('ES_FUT', 'ES future'), ('ETF_NAV', 'ETF NAV proxy'), ('ADR', 'ADR line'), ('HYPERLIQUID', 'Hyperliquid perp'), ('BYBIT', 'Bybit perp'), ('TRADE_XYZ', 'trade.xyz perp'), ('OSTIUM', 'Ostium perp')], max_length=16),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Effective weight this tick: zero when excluded, per Binance's staleness rule."),
        ),
    ]
