# Generated by Django 5.2.17 on 2026-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_priceobservation_clamped_priceobservation_raw_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskpolicy',
            name='velocity_cooldown_seconds',
            field=models.PositiveIntegerField(default=10, help_text='DERIVED. After a velocity pause ends, the velocity check may not fire again for this long. Without it the protected macro cascade paused 56 times in 5-second bursts with 3 seconds of trading between them, and each reopen dumped queued liquidations back into the book: 83 price swings of 50 bps or more against 4 with no controls at all. CFTC/FIA specify the layer and its ~5s pause but no re-arm rule. Tuning started at 30s by instruction; at 20s and above the layer fires twice, the cascade runs through continuous trading, and controls-on loses to controls-off on unnecessary liquidations in upi_settlement_delay. 10s, with escalation, is the longest cooldown that keeps the controls ahead in every scenario. Provisional: re-tuned once reopens go through the call auction.'),
        ),
        migrations.AddField(
            model_name='riskpolicy',
            name='velocity_escalation_multiplier',
            field=models.FloatField(default=4.0, help_text="DERIVED. If the price is still moving too fast when the cooldown ends, the next velocity pause is this many times longer than the last (5s, 20s, 80s), capped at the circuit breaker's 120s pause. Repeating the same short pause into a market that has not calmed is what produced the zig-zag. The escalation resets once a full velocity window passes calm after cooldown."),
        ),
    ]
