# Generated by Django 5.2.17 on 2026-09-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_velocity_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskpolicy',
            name='velocity_cooldown_seconds',
            field=models.PositiveIntegerField(default=10, help_text="DERIVED. After a velocity pause ends, the velocity check may not fire again for this long. Without it the protected macro cascade paused 56 times in 5-second bursts with 3 seconds of trading between them, and each reopen dumped queued liquidations back into the book: 83 price swings of 50 bps or more against 4 with no controls at all. CFTC/FIA specify the layer and its ~5s pause but no re-arm rule. Tuned from 30s against all six scenarios with reopens through the call auction: from 20s up the throttle drains the queue in continuous trading before the layer re-arms, and controls-on loses to controls-off on unnecessary liquidations in upi_settlement_delay. 10s is the longest value that keeps the controls ahead everywhere. The deeper cause is that the 20% TWAP participation moves price ~88 bps/s against a velocity trigger of ~40 bps/s, so the engine's own permitted pace trips the layer; see ARCHITECTURE.md."),
        ),
        migrations.CreateModel(
            name='DepthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('mid', models.FloatField()),
                ('best_bid', models.FloatField()),
                ('best_ask', models.FloatField()),
                ('bucket_bps', models.PositiveSmallIntegerField()),
                ('bids', models.JSONField(help_text='INR notional per bucket, nearest the touch first.')),
                ('asks', models.JSONField(help_text='INR notional per bucket, nearest the touch first.')),
                ('depth_pct_of_baseline', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depth', to='core.simrun')),
            ],
            options={
                'verbose_name': 'depth snapshot',
                'ordering': ('run', 'tick'),
                'unique_together': {('run', 'tick')},
            },
        ),
        migrations.CreateModel(
            name='LiquidationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('account', models.CharField(help_text='Account handle within the run.', max_length=32)),
                ('stage', models.CharField(choices=[('partial', 'Partial (stage one, fee-free)'), ('market', 'Market (full close, no two-stage)'), ('backstop', 'Backstop (below 2/3 MM, MM forfeited)'), ('adl', 'ADL (a winner force-closed)')], max_length=10)),
                ('qty', models.FloatField()),
                ('notional_inr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('via_auction', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False, help_text='The account had no position left after this tick.')),
                ('survived_at_reference', models.BooleanField(default=False, help_text='APE criterion 3: solvent at the Reference Composite.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to='core.simrun')),
            ],
            options={
                'verbose_name': 'liquidation record',
                'ordering': ('run', 'tick', 'id'),
                'indexes': [models.Index(fields=['run', 'tick'], name='core_liquid_run_id_1bc750_idx'), models.Index(fields=['run', 'account'], name='core_liquid_run_id_b986be_idx')],
            },
        ),
    ]
