# Generated by Django 5.2.17 on 2026-09-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_liquidations_and_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='drill_clock_s',
            field=models.PositiveIntegerField(default=0, help_text="Seconds on the playbook clock, T+0 to T+3600. The market event runs for the scenario's 10-12 minutes, one engine tick per second; the response -- quantify, remediate, reopen, hand over -- runs to T+60."),
        ),
        migrations.AlterField(
            model_name='incidentaction',
            name='action_type',
            field=models.CharField(choices=[('DECLARE', 'T+0 Declare — SEV-1, I am IC'), ('PROTECT_SWITCH', 'T+2 Protect Switch — reduce-only, throttle, 3x'), ('REDUCE_ONLY', 'T+2 Reduce-only'), ('PAUSE_LIQUIDATIONS', 'T+2 Pause liquidations (oracle suspect)'), ('LIQ_THROTTLE', 'T+2 Liquidation TWAP throttle'), ('LEVERAGE_CAP', 'T+2 Cut max leverage'), ('WIDEN_BANDS', 'T+2 Widen price bands'), ('HALT_MARKET', 'haltTrading — settles everyone at mark'), ('SNAPSHOT_EVIDENCE', 'T+3 Preserve evidence'), ('PUBLISH_UPDATE', 'T+5 Publish update'), ('CLASSIFY', 'T+15 Classify A–G'), ('QUANTIFY', 'T+15–30 Quantify the affected set'), ('OPEN_CLAIMS', 'T+30 Open claims portal'), ('PROVISIONAL_CREDIT', 'T+30 Push provisional credit'), ('STAGED_REOPEN', 'T+45 Staged reopen through auction'), ('RESOLVE', 'T+60 Handover')], max_length=24),
        ),
    ]
