# Generated by Django 5.2.17 on 2026-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_war_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='The three APE criteria with their numbers, the decisive fill, and the layer signals behind the category. What a user would need to re-derive the decision from the published tape.'),
        ),
        migrations.AddField(
            model_name='incident',
            name='classification_detail',
            field=models.JSONField(blank=True, default=dict, help_text="The classifier's working for the incident-level verdict: headline, evidence and the tape signatures it read. The letter alone is not a verdict anyone can check."),
        ),
    ]
