# Generated by Django 5.2.17 on 2026-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_forensics'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='remediation_detail',
            field=models.JSONField(blank=True, default=dict, help_text='The funding waterfall as computed when claims were opened: total claimed, the cap, what each source drew, the pro-rata ratio if the cap bound, and the provisional-credit deadline.'),
        ),
        migrations.AddField(
            model_name='simrun',
            name='modelled_claims',
            field=models.JSONField(blank=True, default=dict, help_text="What this run would owe under the published remedy formulas: the classifier's verdict and the uncapped cash claims total. Read by 'Recalibrate from simulation' to size the Incident Reserve."),
        ),
    ]
