# Generated by Django 5.2.17 on 2026-09-26 02:26

from django.db import migrations, models


def published_were_approved(apps, schema_editor):
    CommsUpdate = apps.get_model("core", "CommsUpdate")
    CommsUpdate.objects.filter(is_published=True).update(approval="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remediation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commsupdate',
            name='approval',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Awaiting the IC'), ('APPROVED', 'Approved'), ('REJECTED', 'Sent back')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='approved_by',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='audience',
            field=models.CharField(choices=[('PUBLIC', 'Everyone'), ('AFFECTED', 'Affected users'), ('VENUE', 'The venue (Hyperliquid)'), ('REGULATOR', 'Regulators')], default='PUBLIC', max_length=12),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='drafted_by',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='guardrails',
            field=models.JSONField(blank=True, default=list, help_text="The language guardrails' findings when it was last checked. Blocks stop approval."),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='solvency_verified',
            field=models.BooleanField(default=False, help_text="OPS attests solvency was reconciled. Without it, 'your funds are safe' is blocked."),
        ),
        migrations.AddField(
            model_name='commsupdate',
            name='template',
            field=models.CharField(blank=True, help_text='The template it started from, if any.', max_length=32),
        ),
        migrations.RunPython(published_were_approved, migrations.RunPython.noop),
    ]
