# Generated by Django 5.2.17 on 2026-09-26 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_comms_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_fingerprint", models.CharField(db_index=True, max_length=32)),
                ("seed", models.BigIntegerField()),
                ("control", models.CharField(max_length=40)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("alone", "Only this control on"),
                            ("last_in", "Full stack without it"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The run summary for that stack.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="core.riskpolicy",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="core.scenario",
                    ),
                ),
            ],
            options={
                "verbose_name": "control attribution",
                "ordering": ("scenario", "control", "mode"),
                "unique_together": {
                    ("scenario", "policy_fingerprint", "seed", "control", "mode")
                },
            },
        ),
    ]
